import { redirect } from "next/dist/server/api-utils";
import Head from "next/head";
import Image from "next/image";
import CardStatistics from "../../components/cards/CardStatistics";
import LayoutDashboard from "../../components/layouts/Dashboard";
import Nav from "../../components/Navigation/Nav";
import SideBar from "../../components/Navigation/SideBar";

export default function Home() {
  return (
    <div className="w-full max-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutDashboard>
        <Nav />
        <div className="grid md:grid-cols-12 md:gap-5 mt-10">
          <div className="md:col-span-8 ">
            <div className="grid md:grid-cols-2 lg:grid-cols-3  xl:grid-cols-4 gap-5">
              <CardStatistics
                icon="groups"
                count="34"
                title="Your client  balance"
              />
              <CardStatistics
                icon="donut_large"
                count="1234"
                small="/moth"
                title="Your transaction balance"
              />
              <CardStatistics
                icon="monetization_on"
                title="Your bank balance"
                count="$1234"
              />
              <CardStatistics
                icon="savings"
                count="1804.94"
                small="/month"
                title="Your Facture  balance"
              />
            </div>
            <div className="mt-10">
              <div class="space-y-8 animate-pulse md:space-y-0 md:space-x-8 md:flex md:items-center">
                <div class="flex justify-center items-center w-full h-48 bg-gray-300 rounded sm:w-96 dark:bg-gray-700">
                  <svg
                    class="w-12 h-12 text-gray-200"
                    xmlns="http://www.w3.org/2000/svg"
                    aria-hidden="true"
                    fill="currentColor"
                    viewBox="0 0 640 512"
                  >
                    <path d="M480 80C480 35.82 515.8 0 560 0C604.2 0 640 35.82 640 80C640 124.2 604.2 160 560 160C515.8 160 480 124.2 480 80zM0 456.1C0 445.6 2.964 435.3 8.551 426.4L225.3 81.01C231.9 70.42 243.5 64 256 64C268.5 64 280.1 70.42 286.8 81.01L412.7 281.7L460.9 202.7C464.1 196.1 472.2 192 480 192C487.8 192 495 196.1 499.1 202.7L631.1 419.1C636.9 428.6 640 439.7 640 450.9C640 484.6 612.6 512 578.9 512H55.91C25.03 512 .0006 486.1 .0006 456.1L0 456.1z"></path>
                  </svg>
                </div>
                <div class="w-full">
                  <div class="h-2.5 bg-gray-200 rounded-full dark:bg-gray-700 w-48 mb-4"></div>
                  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[480px] mb-2.5"></div>
                  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 mb-2.5"></div>
                  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[440px] mb-2.5"></div>
                  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[460px] mb-2.5"></div>
                  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[360px]"></div>
                </div>
                <span class="sr-only">Loading...</span>
              </div>
            </div>
          </div>
          <div className="md:col-span-4 row-start-1 md:row-start-auto ">
            <div className="shadow-sm  bg-gradient-to-br from-purple-500 to-pink-500  text-white rounded-3xl p-5">
              <div className="grid md:grid-cols-1 lg:grid-cols-6">
                <span class="material-symbols-outlined text-5xl ">
                  local_convenience_store
                </span>

                <h3 className="xl:text-4xl lg:text-2xl font-bold ">
                  SELECTEDD20211
                </h3>
              </div>
              <div className=" mt-3">
                <p className="mt-3">
                  YOur bank <br /> balance
                </p>
              </div>
            </div>
          </div>
        </div>
      </LayoutDashboard>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const cookies = context.req.cookies;
  /*  if (!cookies.access && !cookies.accessUser) {
    redirect(context.res, 302, "/");
  }
  if (cookies.access) {
    redirect(context.res, 302, "/dashboard/employees");
  } */
  return {
    props: {},
  };
};
