import { redirect } from "next/dist/server/api-utils";
import Head from "next/head";
import Image from "next/image";
import CardStatistics from "../../components/cards/CardStatistics";
import LayoutDashboard from "../../components/layouts/Dashboard";
import Nav from "../../components/Navigation/Nav";
import SideBar from "../../components/Navigation/SideBar";

export default function Home() {
  return (
    <div className="w-full max-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutDashboard>
        <Nav />
        <div className="grid md:grid-cols-12 md:gap-5 mt-10">
          <div className="md:col-span-8 ">
            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5">
              <CardStatistics icon="groups" count="34">
                Your client <br /> balance
              </CardStatistics>
              <CardStatistics icon="donut_large" count="1234" small="/moth">
                Your transaction <br /> balance
              </CardStatistics>
              <CardStatistics icon="monetization_on" count="$1234">
                Your bank <br /> balance
              </CardStatistics>
              <CardStatistics icon="savings" count="1804.94" small="/month">
                Your Facture <br /> balance
              </CardStatistics>
            </div>
          </div>
          <div className="md:col-span-4 row-start-1 md:row-start-auto ">
            <div className="shadow-sm  bg-black  text-white rounded-3xl p-5">
              <div className="flex">
                <span class="material-symbols-outlined text-5xl">
                  local_convenience_store
                </span>

                <h3 className="text-4xl font-bold">SELECTEDD20211</h3>
              </div>
              <div className=" mt-3">
                <p className="mt-3">
                  YOur bank <br /> balance
                </p>
              </div>
            </div>
          </div>
        </div>
      </LayoutDashboard>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const cookies = context.req.cookies;
  /*  if (!cookies.access && !cookies.accessUser) {
    redirect(context.res, 302, "/");
  }
  if (cookies.access) {
    redirect(context.res, 302, "/dashboard/employees");
  } */
  return {
    props: {},
  };
};
